# Generated by Django 6.0.4 on 2026-04-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('action_taken', models.CharField(max_length=50)),
            ],
        ),
    ]
